### ISSUE TITLE
无法打开页面

### ISSUE THREAD

**Issue by feilongjump** [foryoufeng/laravel-generator#4]
你好，我今天按照你的步骤去进行安装，但是却无法打开，以下是我的错误和配置
![image](https://user-images.githubusercontent.com/48574176/73899863-d4daf580-48c8-11ea-82d3-1da9c92f0610.png)
![image](https://user-images.githubusercontent.com/48574176/73899966-284d4380-48c9-11ea-920b-8ab8daebf2dd.png)

**Comment by foryoufeng** [comment]
恩  好的  我这边看看   可能是laravel6之后有一些改动
